name: Deploy my Lambda Function

# trigger on all push events to main branch and runner is ubuntu
on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install linting libraries
        run: |
            cd function
            pip install flake8
      - name: Lint with flake8
        run: |
            # Select identifies which errors should cause the job to fail
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # The exit zero flag will show errors as warnings and not fail the run
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: self-hosted
    needs: lint 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        run: |
          sudo yum install python3
      - name: Install libraries
        run: |
            cd function
            sudo yum –y install python3-pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
